server:
   ssl:
      enabled: false
  
springdoc:
   api-docs:
      path: /api-docs
   pathsToMatch: /rest-api/v1/**
   
furms:
   notification:
      new-policy-template-id: testTemplate
      new-policy-revision-template-id: testTemplate
      new-invitation-template-id: testTemplate
      accepted-invitation-template-id: testTemplate
      rejected-invitation-template-id: testTemplate
      new-application-template-id: testTemplate
      accepted-application-template-id: testTemplate
      rejected-application-template-id: testTemplate
      alarm-resource-usage-template-id: testTemplate
      alarm-resource-usage-without-url-template-id: testTemplate
   invitations:
      expiration-time-in-seconds: 604800
      fenix-form: fenixForm
      site-form: siteForm
      community-form: communityForm
      project-form: projectForm

   unity:
      admin-url: ${furms.unity.url}/rest-admin/v1
      admin-user: furms-rest-client
      admin-password: AdminP@SSword1234!@&
      url: https://localhost:2443
      ssl:
         trust-store: classpath:demoTruststore.jks
         trust-store-password: unicore
      oAuth:
         clientId: oauth-client
         clientSecret: oauth-pass1
   front:
      language: en
   url: https://localhost:${server.port}
   psk:
      centralIdPUser: cidp
      centralIdPSecret: cidppass

spring:
   datasource:
      url: jdbc:h2:file:./target/db/furms;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
      username: sa
      password: sa
      driver-class-name: org.h2.Driver