== Site management

FURMS site acts a resource provider. Site defines resources (which are always site specific in FURMS), and advertises amounts of those resources available to the Fenix infrastructure. 

Additionally site can define policy documents which are need to be accepted in order to access the site or its resources.

=== Site settings

Under site settings menu entry, site administrator can provide details about the site. It is advised to fill up the form, as initially site definition consists of a minimal set of attributes (like name) only.

Site administrator may set a requirement on SSH keys installed by FURMS, to always include the 'from' option (specifying allowed client addresses for the key). If this option is set after some keys without the 'from' option were already installed, FURMS will not auto-remove the offending keys. However, user will be forced to either remove the key from the site or to add the 'from' option upon the next editing of the key. 

What is more site administrator can require users not to reuse previously used SSH keys. 

Site can have a policy document set. Accepting site policy is a prerequisite for any user, to be added to the site. Any policy defined for the site can be selected as a site-wide policy. 

=== Policy documents

Site can define multiple policy documents. A policy document can be used in two places: as a site-wide policy or as a service-specific policy. Policy documents can be provided either as an uploaded PDF file, or can be embedded inside FURMS using rich text editor. 

Policy documents are defined in a single place (Policy Documents menu entry). Assigning policy document to a service is available in serivice's edit view, while selection of a site-wide policy can be performed in site's settings view.

FURMS supports two types of policy document workflows:

* `web based` policies are electronically processed documents, i.e. users can accept them on-line, from the FURMS app.
* `paper` policies need to be printed and physically delivered to site authorities.

Users are asked to check the policy whenever they get access to a resource, which is either on a new site or a new service, for which the policy is defined and was not accepted yet. Regardless of the policy type, user can always read & download its text. In the case of the web policies, direct acceptance is possible by the user. Contrary, the fact that the hand-signed paper policy document was received, must be recorded by site administrator or site support (see <<managing-site-admins>>). This functionality is available after entering into details of users policy acceptance status, in the Policy Documents view.

Policy documents can be updated after creation. Update can be done in two ways:

* As a `silent` update, useful for correcting typos and formatting. In such a case, users who previously accepted the policy won't be notified in any way.
* As an `official` update. Official update triggers requests to users who previously accepted the policy, to review and accept the updated version. Official update is also tracked with a policy `revision number`, which is incremented each time the policy is officially updated.


=== Services

Services are used in FURMS to represent different offerings of a single site. The most important aspect of service is that it can have its own access policy agreement defined. Also each service creates a namespace for its resources.

Computing cluster, data store system or an OpenStack VM service can be examples of services.

Service can have its own policy document. Any of the policy documents defined for the site can be selected.

=== Resource types

Resource type represents resource which have _independent allocations_ and has its usage accounted separately.

Administrator has to decide type and a dependent unit of the resource type. Type defines generic treatment of resource and available units. FURMS supports two generic types _integer_ and _floating point_ as well as two more specific types: _time_ and _data_. 

Units are different for each type. Note that FURMS does not scale the amounts of a given resource type, always the selected Unit is used.  

=== Resource credits

Resource credits are used to express site’s offering to the FURMS managed infrastructure. Credit is an offer of a particular amount of a given resource in a defined timeframe. Credits are further distributed by Fenix administrators to communities and eventually to projects.

Each credit is always based on a single resource type (and therefore is also bound to  a particular service). 

Credit has its lifetime, expired credits can not be allocated to communities or projects, even if were not completely consumed.

Site can control whether credit can be allocated in multiple parts or just as a single one. In the later case it must be allocated to a single community and to a single project in this community.

Finally credits can be marked as _granted to all project members_. Allocation derived from credits created with this flag will not have separate access authorization: each project member will be able to use it, without any further actions.


=== Site agent connection and requests

{versionlimit} This functionality is available only partially, allowing site administrators to check whether the agent is up and connected.

[[managing-site-admins]]
=== Managing site administrators

FURMS allows for multiple users with the site administrator role. Each site administrator can add (and remove) other administrators from the "Site administrators" view. 

Additionally the view allows for adding users with the `site support` role. Such users will be able to access only the Policy Documents view and record the fact that a hand-signed paper policy document was received.

A new administrator can be invited by providing an email address of the invitation recipient. The invited person must possess a Fenix infrastructure account. 

Note that removing the last administrator is not allowed.

=== REST API access credentials

include::rest-api-access.adoc[]