== End User support

Every user that signs into FURMS has access to her/his FURMS profile & settings view. For the users who have no additional roles, this is the only accessible view, others can activate it from the top-right view chooser.

User settings allows every FURMS user to check:

* personal information which is exposed to FURMS by the Fenix infrastructure,
* user's sites and projects,
* SSH keys management.

=== Sites

Sites view shows all sites to which access is granted. Note that if access to a site is granted through several projects, then multiple entries will show up, for each project. 

Table shows the local user identifier at the site as well as the site-provided information on connection and other special access rules.

=== Projects

The projects view provides a list of all FURMS projects. By default only the projects where the user is a member are shown. 

For each project of the user, it is possible to drill down and check available allocations in that project.

It is possible to apply for a membership in a project. In order to do so, first the filter to include "Remaining projects" must be selected. Then after locating a project of interest an access application can be submitted.    

==== Resource usage

It is possible to inspect the details of actual resource usage per each resource allocation in any of the projects.

High level overview of the resource consumption is presented in allocations table itself as a small progress bar-like widget. More detailed information is available after navigating to the charts view, from allocation row menu.

Chart is showing the resource usage reported by a site under the given allocation. What is more the actual allocation chunks as assigned by site are also shown as a red line. Finally, if an alarm is defined, its threshold level is also shown as an orange line.

If the visual representation is not detailed enough, it is possible to export raw information on all recorded consumption records. FURMS can export the data either to a CSV or JSON files, with a self-explanatory syntax. 


=== SSH keys management

The 'SSH Keys' view allows for managing public SSH keys across all sites to which access is granted via project membership.

FURMS allows to define separate keys per each site, or to share the same key across several sites. Multiple keys can be installed for each site.

Format of SSH key is the same as used in the +authorized_keys+ file of SSH. See http://man.openbsd.org/sshd.8#AUTHORIZED_KEYS_FILE_FORMAT for more details.

Update of a key removes the old value from sites and then installs an updated one.

NOTE: Some sites may require to set the 'from' option in the SSH key. Keys without that option can't be added to sites requiring the 'from' option.

=== Policy documents

Sites providing resources may require acceptance of their policy document(s). Typically there is a single document per site, and sometimes there are additional documents per a site-offered service.

Typically the pending policy documents can be accepted from FURMS "User Settings" -> "Policy Documents" view. Site may also require delivery of physical paper document with a hand signature. In such case FURMS will provide the necessary document with an ability to download it.

Note that lack of acceptance of the site's policy document will prevent user account creation on the site.

In case when a previously accepted document is updated, a notification will be delivered asking for an acceptance of the updated version.
