== Fenix federation management

Fenix administrator is responsible for:

* creating sites,
* creating communities,
* distributing site provided resource credits to communities.

=== Managing sites

Fenix admin can create sites providing only the basic information: site name. Additional site attributes are supposed to be setup by the site admin.

After creating a site, Fenix admin should provide at least a single administrator for the site. The appropriate view can be activated from the site's context menu "Administrators". From there the Fenix admin can freely add and remove site administrators. 

NOTE: Site administrators can also themselves manage administrators of their site, so the Fenix admin is not the only person controlling the set of administrators. However, setting the initial site admin must be always performed by the Fenix admin.

include::snippets/invite-admin-generic.adoc[]


=== Managing communities

Fenix admin can create communities providing site name, description and logo. Community settings can be also changed subsequently by community admins and therefore only the name of a created community is mandatory.

After creating a community, Fenix admin should provide at least a single administrator for it. The appropriate view can be activated from the community's context menu "Administrators". From there the Fenix admin can freely add and remove community administrators. 

NOTE: Community administrators can also themselves manage administrators of their community, so the Fenix admin is not the only person controlling the set of administrators. However, setting the initial community admin must be always performed by the Fenix admin.

include::snippets/invite-admin-generic.adoc[]

=== Managing Fenix administrators

FURMS allows for having multiple users with the Fenix administrator role. Each Fenix admin can add (and remove) other administrators from the "Fenix administrators" view. 

include::snippets/invite-admin-generic.adoc[]

Note that removing the last administrator is not allowed.

=== Distributing resources to communities

Distribution of resource credits provided by sites can be performed from two parts of the FURMS user interface. 

The typical way to distribute credits starts at the Fenix administrator dashboard. Dashboard shows all resource credits. By default only the not-fully distributed and valid credits are shown, though it is possible to show also all excluded ones. Fenix admin can use the (+) button on each credit to create an allocation from it. When creating allocation this way, the target community has to be selected.

The other way to create allocations from credits is to start from a target community, in the Communities view. After selecting a community and navigating to its _Allocations_ tab, Fenix administrator can create an allocation for that community. When creating allocation this way, the resource credit needs to be selected. Interface allows for using multiple level of filters to easily find the desired credit.    

=== Resource usage

Fenix administrators can see the details of resource usage per each community resource allocation.

High level overview of the resource consumption is presented in allocations table itself as a small progress bar-like widget. More detailed information is available after navigating to the charts view, from allocation row menu.

Chart is showing the resource usage reported by a site under the given allocation.

If the visual representation is not detailed enough, it is possible to export raw information on all recorded consumption records. FURMS can export the data either to a CSV or JSON files, with a self-explanatory syntax. 

=== Audit log

FURMS records all important changes of state in journal, called audit log. Fenix administrator can access this journal from the "Audit Log" main menu menu entry.

Audit log provides a range of filters allowing to narrow down presented set of log records. It is possible to filter by time, user (who triggered an operation), type of operation, specific action and finally perform a free-text search. 

Some of the presented records can be expanded to inspect an additional,  operation specific information. For instance in case of `PROJECT_ALLOCATION` record with `Create` action, it is possible to check identifiers of the created allocation, project and community allocation basing on which the project allocation was created. Amount and name of the allocation are also provided.  

=== REST API access credentials

include::rest-api-access.adoc[]