== Site management

FURMS site acts a resource provider. Site defines resources (which are always site specific in FURMS), and advertises amounts of those resources available to the Fenix infrastructure. 

Additionally site can define policy documents which are need to be accepted in order to access the site or its resources.

=== Site settings

Under site settings menu entry, site administrator can provide details about the site. It is advised to fill up the form, as initially site definition consists of a minimal set of attributes (like name) only.

Site administrator may set a requirement on SSH keys installed by FURMS, to always include the 'from' option (specifying allowed client addresses for the key). If this option is set after some keys without the 'from' option were already installed, FURMS will not auto-remove the offending keys. However, user will be forced to either remove the key from the site or to add the 'from' option upon the next editing of the key.  

=== Policy documents

{versionlimit} This functionality is not available yet.

=== Services

{versionlimit} This functionality is not available yet.

=== Resource types

{versionlimit} This functionality is not available yet.

=== Resource credits

{versionlimit} This functionality is not available yet.

=== Site agent connection and requests

{versionlimit} This functionality is not available yet.

=== Managing site administrators

FURMS allows for multiple users with the site administrator role. Each site administrator can add (and remove) other administrators from the "Site administrators" view. 

{versionlimit} Adding site administrators is currently limited to users who has signed in to FURMS at least once.

