== End User support

Every user that signs into FURMS has access to her/his FURMS profile & settings view. For the users who have no additional roles, this is the only accessible view, others can activate it from the top-right view chooser.

User settings allows every FURMS user to check:

* personal information which is exposed to FURMS by the Fenix infrastructure,
* user's sites and projects,
* SSH keys management.

=== Sites

Sites view shows all sites to which access is granted. Note that if access to a site is granted through several projects, then multiple entries will show up, for each project. 

Table shows the local user identifier at the site as well as the site-provided information on connection and other special access rules.

=== Projects

The projects view provides a list of projects. By default only the projects where the user is a member are shown. 

{versionlimit} It is also possible to see all projects, as in future FURMS will support project applications.

For each project of the user, it is possible to drill down and check available allocations in that project.

=== SSH keys management

The 'SSH Keys' view allows for managing public SSH keys across all sites to which access is granted via project membership.

FURMS allows to define separate keys per each site, or to share the same key across several sites. Multiple keys can be installed for each site.

Format of SSH key is the same as used in the +authorized_keys+ file of SSH. See http://man.openbsd.org/sshd.8#AUTHORIZED_KEYS_FILE_FORMAT for more details.

Update of a key removes the old value from sites and then installs an updated one.

NOTE: Some sites may require to set the 'from' option in the SSH key. Keys without that option can't be added to sites requiring the 'from' option. 