== Community management

FURMS community groups closely related projects and organizes the process of allocating resources to them. 

=== Managing projects

Community administrator can create projects providing set of initial project settings. Selected project settings can be also changed subsequently by project administrators.

When creating a project, community administrator needs to setup project leader, who will also become the initial project administrator. Additional administrators can be also setup after activating the "Administrators" option from the project's context menu.

NOTE: Project administrators can also themselves manage administrators of their project, and so community administrator is not the only person controlling the set of administrators.

include::snippets/invite-admin-generic.adoc[]
Selection of existing users is limited to the users already belonging to the community.

=== Managing community administrators

FURMS allows for having multiple users with the community administrator role. Each community administrator can add (and remove) other administrators from the "Community Administrators" view. 

include::snippets/invite-admin-generic.adoc[]
Selection of existing users is limited to the users already belonging to the community.

Note that removing the last administrator is not allowed.

=== Managing community metadata

Community name, description and logo can be modified at any time. It can be performed from the "Settings" view.

=== Distributing resources to projects

Distribution of community resource allocations to projects can be performed in two different ways. 

The typical path to distribute available resource allocations starts at the community administrator dashboard. Dashboard shows all resource allocations of the community. By default only the not-fully distributed and valid allocations are shown, though it is possible to show also the ones excluded by default. Community admin can use the (+) button on each community allocation to create a project allocation from it. When creating allocation this way, the target project has to be selected.

The other way to create project allocations is to start from a target project, in the Projects view. After selecting a project and navigating to its _Allocations_ tab, community administrator can create an allocation for that project. When creating allocation this way, one of community allocations needs to be selected. 

=== REST API access credentials

include::rest-api-access.adoc[]