== Community management

FURMS community groups closely related projects and organizes the process of allocating resources to them. 

=== Managing projects

Community administrator can create projects providing set of initial project settings. Selected project settings can be also changed subsequently by project administrators.

When creating a project, community administrator needs to setup project leader, who will also become the initial project administrator. Additional administrators can be also setup after activating the "Administrators" option from the project's context menu.

NOTE: Project administrators can also themselves manage administrators of their project, and so community administrator is not the only person controlling the set of administrators.

include::snippets/invite-admin-generic.adoc[]
Selection of existing users is limited to the users already belonging to the community.

=== Managing community administrators

FURMS allows for having multiple users with the community administrator role. Each community administrator can add (and remove) other administrators from the "Community Administrators" view. 

include::snippets/invite-admin-generic.adoc[]
Selection of existing users is limited to the users already belonging to the community.

Note that removing the last administrator is not allowed.

=== Managing community metadata

Community name, description and logo can be modified at any time. It can be performed from the "Settings" view.

=== Distributing resources to projects

Distribution of community resource allocations to projects can be performed in two different ways. 

The typical path to distribute available resource allocations starts at the community administrator dashboard. Dashboard shows all resource allocations of the community. By default only the not-fully distributed and valid allocations are shown, though it is possible to show also the ones excluded by default. Community admin can use the (+) button on each community allocation to create a project allocation from it. When creating allocation this way, the target project has to be selected.

The other way to create project allocations is to start from a target project, in the Projects view. After selecting a project and navigating to its _Allocations_ tab, community administrator can create an allocation for that project. When creating allocation this way, one of community allocations needs to be selected. 

=== Resource usage

Community administrators can see the details of resource usage per each project resource allocation.

High level overview of the resource consumption is presented in allocations table itself as a small progress bar-like widget. More detailed information is available after navigating to the charts view, from allocation row menu.

Chart is showing the resource usage reported by a site under the given allocation.

If the visual representation is not detailed enough, it is possible to export raw information on all recorded consumption records. FURMS can export the data either to a CSV or JSON files, with a self-explanatory syntax. 

=== Managing groups

FURMS allows community administrators to create groups and control membership of community users in the groups. 

There are no limits on membership in groups, any community member can be a member of zero, one or many groups. The sole restriction is that only existing community users can be added to a group (i.e. users of any of the community projects and community admins). Adding and removing a user to a group does not require user's consent.

Group membership is not changing the way how FURMS works in any way. It is, however, exposed on the REST APIs: both for the Fenix Central IdP and over Community REST API.


=== REST API access credentials

include::rest-api-access.adoc[]