== Community management

FURMS community groups closely related projects and organizes the process of allocating resources to them. 

=== Managing projects

Community administrator can create projects providing set of initial project settings. Selected project settings can be also changed subsequently by project administrators.

When creating a project, community administrator needs to setup project leader, who will also become the initial project administrator. Additional administrators can be also setup after activating the "Administrators" option from the project's context menu.

NOTE: Project administrators can also themselves manage administrators of their project, and so community administrator is not the only person controlling the set of administrators.

{versionlimit} Adding project administrators is currently limited to users who has signed in to FURMS at least once.

=== Managing community administrators

FURMS allows for having multiple users with the community administrator role. Each community administrator can add (and remove) other administrators from the "Community Administrators" view. 

{versionlimit} Adding community administrators is currently limited to users who has signed in to FURMS at least once.


=== Managing community metadata

Community name, description and logo can be modified at any time. It can be performed from the "Settings" view.

=== Distributing resources to projects

{versionlimit} This functionality is not available yet.