/*
 * Copyright (c) 2020 Bixbit s.c. All rights reserved.
 * See LICENSE file for licensing information.
 */

package io.imunity.furms.domain.roles;

public enum Capability {
	AUTHENTICATED, PROFILE, SITE_READ, SITE_WRITE, SITE_ADMINS_MANAGEMENT, COMMUNITY_READ, COMMUNITY_WRITE,
	FENIX_ADMINS_MANAGEMENT, PROJECT_READ, PROJECT_WRITE, COMMUNITY_ADMINS_MANAGEMENT, PROJECT_MEMBER_MANAGEMENT,
	PROJECT_ADMINS_MANAGEMENT
}
