/**
 * This file contains project specific customizations for the webpack build.
 * It is autogenerated if it didn't exist or if it was made for an older
 * incompatible version.
 *
 * Defaults are provided in an autogenerated webpack.generated.js file and used by this file.
 * The webpack.generated.js file is overwritten on each build and no customization can be done there.
 */
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

const mergedConfig = merge(flowDefaults);
mergedConfig.resolve.alias['@vaadin/vaadin-combo-box/src/vaadin-combo-box-placeholder.js'] = '@vaadin/combo-box/src/vaadin-combo-box-placeholder.js';
module.exports = mergedConfig;

