version: '3.7'

services:
  db-furms-postgres:
    image: postgres:11.4
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: furms
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: