/*
 * Copyright (c) 2020 Bixbit s.c. All rights reserved.
 * See LICENSE file for licensing information.
 */

package io.imunity.furms.domain.authz.roles;

public enum Capability {
	USERS_MAINTENANCE,
	AUTHENTICATED, 
	PROFILE, 
	FENIX_ADMINS_MANAGEMENT,  
	
	COMMUNITY_READ, COMMUNITY_WRITE, COMMUNITY_ADMINS_MANAGEMENT, 

	SITE_READ, SITE_WRITE, SITE_ADMINS_MANAGEMENT, 
	
	PROJECT_READ, 
	PROJECT_WRITE, 
	PROJECT_LIMITED_WRITE,
	PROJECT_MEMBER_MANAGEMENT,
	PROJECT_ADMINS_MANAGEMENT, 
	
	READ_ALL_USERS
}
